export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_OK = "USER_LOGIN_OK";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_OK = "USER_LOGOUT_OK";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const USER_SINGUP = "USER_SINGUP";
export const USER_SINGUP_OK = "USER_SINGUP_OK";
export const USER_SINGUP_ERROR = "USER_SINGUP_ERROR";

export const USER_RECOVERPASSWORD = "USER_RECOVERPASSWORD";
export const USER_RECOVERPASSWORD_OK = "USER_RECOVERPASSWORD_OK";
export const USER_RECOVERPASSWORD_ERROR = "USER_RECOVERPASSWORD_ERROR";

export const USER_NEWPASSWORD = "USER_NEWPASSWORD";
export const USER_NEWPASSWORD_OK = "USER_NEWPASSWORD_OK";
export const USER_NEWPASSWORD_ERROR = "USER_NEWPASSWORD_ERROR";


//Fillter
export const FILTER_ONCHAGE = "FILTER_ONCHAGE";
//Checkbox
export const CHECKBOX_SELECT = "CHECKBOX_SELECT";
