export const data = [
    {
        Funnel_Status: "1",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "2",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "3",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "4",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "5",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "6",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "7",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "8",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "9",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "10",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "11",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "12",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "13",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "14",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    },
    {
        Funnel_Status: "15",
        Last_Update: "",
        Next_Action: "",
        FollowUp: "",
        DecisionMaker: "Guillermo",
        LastName: "saboit",
        Company_Area: "marketing",
        Company_Position:"manager",
        Personal_Mail: "",
        Personal_CompanyMail:"gbauzas@tracsa.com.ar",
        CellPhone_Whatsapp:"54 9 341 586-8889",
        Skype_User: "",
        HangOut_User: "",
        Linkedin_URL: "https://www.linkedin.com/in/guillermo-bauzas-a634b9151/",
        Picture_URL: "",
        Facebook_URL: "",
        Instagram_URL: "",
        Interests:"Football, Girls, TVs",
        Sex: "male",
        NSE: "High",
        Birthday: "12/10/19",
        Media_Consumption: "Status_Whatsapp, Linkedin",
        Company_LinkedIn_URL: "https://www.linkedin.com/company/tracsa-&-tracbras/",
        Company_Name: "Tracsa",
        Potential_Size: "big",
        Company_Sector: "Agroindustry",
        Company_Products: "",
        Web_URL: "www.tracsa.com.ar",
        Company_Phone: "",
        Sucursal_Location: "Cordoba 2479",
        City: "Santa Fe",
        State: "Santa Fe",
        Country: "",
        NextPurchase_Date: "",
        Satisfaction_DM: "Great",
        Operator_MailID: "cbauzas@wulpers.com",
        Countable_Number: "",
        DM_Countable: "Viviana Corizo",
        Personal_CountableMail: "vtedeschi@tracsa.com.ar",
        CellPhone_Countable: "",
        Payment_Date: "10/09/19",
        Frecuency: "Unique",
        Payment_Method: "Bank_Tansfer",
        Payment_Ammount: "10000",
        Status_Countable: "Delayed",
        Payment_Description: ""
    }
]
